[phases.setup]
  nixPkgs = ["...", "cacert", "openssl"]

[phases.install]
  cmds = ["apt-get update -y && apt-get install -y ca-certificates openssl && update-ca-certificates || true", "npm ci"]

[phases.build]
  cmds = ["npm run build"]

[start]
  cmd = "node dist/main"
